repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1 # Use the latest stable version
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
- repo: local
  hooks:
  - id: pytest
    name: pytest
    entry: pytest
    language: system
    types: [python]
    pass_filenames: false
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.5.0
  hooks:
  - id: detect-secrets
    args: ['--baseline', '.secrets.baseline']
    exclude: package.lock.json
- repo: https://github.com/psf/black
  rev: main
  hooks:
  - id: black
- repo: https://github.com/PyCQA/pylint
  rev: main
  hooks:
  - id: pylint
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: main
  hooks:
  - id: mypy
- repo: https://github.com/pre-commit/mirrors-isort
  rev: main
  hooks:
  - id: isort
- repo: https://github.com/PyCQA/bandit
  rev: main
  hooks:
  - id: bandit
